// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/21 01:07:59
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Administrator/Desktop/trader/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/trader/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/trader/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Administrator/Desktop/trader/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Administrator/Desktop/trader/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;